---
abstract: 'RSA public-key cryptosystem.'
author:
  - 'Vipul Ved Prakash <mail@vipul.net>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Crypt-RSA
no_index:
  directory:
    - inc
    - t
requires:
  Class::Loader: 2.00
  Convert::ASCII::Armour: 0
  Crypt::Blowfish: 0
  Crypt::CBC: 0
  Crypt::Primes: 0.38
  Crypt::Random: 0.34
  Data::Buffer: 0
  Data::Dumper: 0
  Digest::MD2: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  Math::Pari: 2.001804
  Sort::Versions: 0
  Tie::EncryptedHash: 0
  perl: 5.6.0
version: 1.97
